import turtle

#第一个矩形
turtle.penup()
turtle.goto(-200,200)
turtle.pendown()
turtle.width(5)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.hideturtle()
turtle.ht()

#第二个矩形
turtle.penup()
turtle.goto(30,200)
turtle.pendown()
turtle.width(5)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.hideturtle()
turtle.ht()

#第三个矩形
turtle.penup()
turtle.goto(-200,-30)
turtle.pendown()
turtle.width(5)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.hideturtle()
turtle.ht()

#第四个矩形
turtle.penup()
turtle.goto(30,-30)
turtle.pendown()
turtle.width(5)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.hideturtle()
turtle.ht()

